create table jpa.courses (course_name varchar(255) not null, course_city varchar(255), course_state varchar(255), primary key (course_name));
create table jpa.events (event_name varchar(255) not null, event_end_date date, event_location varchar(255), event_start_date date, primary key (event_name));
create table jpa.losses (loss_id uuid not null, result varchar(255), match_id uuid, player_id varchar(255), team_name varchar(255), primary key (loss_id));
create table jpa.matches (match_id uuid not null, match_name varchar(255), round_id uuid, primary key (match_id));
create table jpa.matches_players (singles_match_list_match_id uuid not null, player_list_player_id varchar(255) not null);
create table jpa.matches_teams (match_list_match_id uuid not null, team_list_team_name varchar(255) not null);
create table jpa.players (player_id varchar(255) not null, password_hash varchar(255), player_age int4 not null, player_city varchar(255), player_first_name varchar(255), player_handicap int4 not null, player_last_name varchar(255), player_nickname varchar(255), player_state varchar(255), role varchar(255), primary key (player_id));
create table jpa.players_teams (player_list_player_id varchar(255) not null, team_list_team_name varchar(255) not null);
create table jpa.rounds (round_id uuid not null, round_name varchar(255), course_name varchar(255), event_name varchar(255), primary key (round_id));
create table jpa.scores (score_id uuid not null, score int4, match_id uuid, player_id varchar(255), round_id uuid, primary key (score_id));
create table jpa.teams (team_name varchar(255) not null, primary key (team_name));
create table jpa.wins (win_id uuid not null, result varchar(255), match_id uuid, player_id varchar(255), team_name varchar(255), primary key (win_id));
alter table if exists jpa.losses add constraint FKkv9n2335uc35akmhey7tm4go3 foreign key (match_id) references jpa.matches;
alter table if exists jpa.losses add constraint FK6xlt75yjb7h85mt4fx2v2jhi3 foreign key (player_id) references jpa.players;
alter table if exists jpa.losses add constraint FK4mrkn0rxbvwcd4yvmjbc9f6su foreign key (team_name) references jpa.teams;
alter table if exists jpa.matches add constraint FKjqepgamspeqo5q36vffq2h593 foreign key (round_id) references jpa.rounds;
alter table if exists jpa.matches_players add constraint FKbgtb5jrbkdorqf43u9ouo8fk4 foreign key (player_list_player_id) references jpa.players;
alter table if exists jpa.matches_players add constraint FK6owtyfg7v8d6yogyep3mogvl6 foreign key (singles_match_list_match_id) references jpa.matches;
alter table if exists jpa.matches_teams add constraint FKslql8hsp3pw67xxcm26fxbtus foreign key (team_list_team_name) references jpa.teams;
alter table if exists jpa.matches_teams add constraint FK3lnqde0lgwh1iwulcjq18hrkr foreign key (match_list_match_id) references jpa.matches;
alter table if exists jpa.players_teams add constraint FKsnpj8wdrfbifdxlkssfxx8xto foreign key (team_list_team_name) references jpa.teams;
alter table if exists jpa.players_teams add constraint FKaxgvdteciq4gdlssvi2s4ce1q foreign key (player_list_player_id) references jpa.players;
alter table if exists jpa.rounds add constraint FKlbene8twdhl7tqe4qyryx9yn9 foreign key (course_name) references jpa.courses;
alter table if exists jpa.rounds add constraint FKmpt307dasls8sg6w3288a0a1t foreign key (event_name) references jpa.events;
alter table if exists jpa.scores add constraint FKmhr6nu0xje0kgubcx0j405gwq foreign key (match_id) references jpa.matches;
alter table if exists jpa.scores add constraint FK4akpbasxcjp3h2uind72q1gqm foreign key (player_id) references jpa.players;
alter table if exists jpa.scores add constraint FKs3t291q06nrji21wr6m8n9gvs foreign key (round_id) references jpa.rounds;
alter table if exists jpa.wins add constraint FKr08ev1nsa6ve7mqccee0m6lwi foreign key (match_id) references jpa.matches;
alter table if exists jpa.wins add constraint FK9ibuqdsn0db7pqadj02bpw23i foreign key (player_id) references jpa.players;
alter table if exists jpa.wins add constraint FK6wd0kd6cat72krn1jrhp26d6h foreign key (team_name) references jpa.teams;
create table jpa.courses (course_name varchar(255) not null, course_city varchar(255), course_state varchar(255), primary key (course_name));
create table jpa.events (event_name varchar(255) not null, event_end_date date, event_location varchar(255), event_start_date date, primary key (event_name));
create table jpa.losses (loss_id uuid not null, result varchar(255), match_id uuid, player_id varchar(255), team_name varchar(255), primary key (loss_id));
create table jpa.matches (match_id uuid not null, match_name varchar(255), round_id uuid, primary key (match_id));
create table jpa.matches_players (singles_match_list_match_id uuid not null, player_list_player_id varchar(255) not null);
create table jpa.matches_teams (match_list_match_id uuid not null, team_list_team_name varchar(255) not null);
create table jpa.players (player_id varchar(255) not null, password_hash varchar(255), player_age int4 not null, player_city varchar(255), player_first_name varchar(255), player_handicap int4 not null, player_last_name varchar(255), player_nickname varchar(255), player_state varchar(255), role varchar(255), primary key (player_id));
create table jpa.players_teams (player_list_player_id varchar(255) not null, team_list_team_name varchar(255) not null);
create table jpa.rounds (round_id uuid not null, round_name varchar(255), course_name varchar(255), event_name varchar(255), primary key (round_id));
create table jpa.scores (score_id uuid not null, score int4, match_id uuid, player_id varchar(255), round_id uuid, primary key (score_id));
create table jpa.teams (team_name varchar(255) not null, primary key (team_name));
create table jpa.wins (win_id uuid not null, result varchar(255), match_id uuid, player_id varchar(255), team_name varchar(255), primary key (win_id));
alter table if exists jpa.losses add constraint FKkv9n2335uc35akmhey7tm4go3 foreign key (match_id) references jpa.matches;
alter table if exists jpa.losses add constraint FK6xlt75yjb7h85mt4fx2v2jhi3 foreign key (player_id) references jpa.players;
alter table if exists jpa.losses add constraint FK4mrkn0rxbvwcd4yvmjbc9f6su foreign key (team_name) references jpa.teams;
alter table if exists jpa.matches add constraint FKjqepgamspeqo5q36vffq2h593 foreign key (round_id) references jpa.rounds;
alter table if exists jpa.matches_players add constraint FKbgtb5jrbkdorqf43u9ouo8fk4 foreign key (player_list_player_id) references jpa.players;
alter table if exists jpa.matches_players add constraint FK6owtyfg7v8d6yogyep3mogvl6 foreign key (singles_match_list_match_id) references jpa.matches;
alter table if exists jpa.matches_teams add constraint FKslql8hsp3pw67xxcm26fxbtus foreign key (team_list_team_name) references jpa.teams;
alter table if exists jpa.matches_teams add constraint FK3lnqde0lgwh1iwulcjq18hrkr foreign key (match_list_match_id) references jpa.matches;
alter table if exists jpa.players_teams add constraint FKsnpj8wdrfbifdxlkssfxx8xto foreign key (team_list_team_name) references jpa.teams;
alter table if exists jpa.players_teams add constraint FKaxgvdteciq4gdlssvi2s4ce1q foreign key (player_list_player_id) references jpa.players;
alter table if exists jpa.rounds add constraint FKlbene8twdhl7tqe4qyryx9yn9 foreign key (course_name) references jpa.courses;
alter table if exists jpa.rounds add constraint FKmpt307dasls8sg6w3288a0a1t foreign key (event_name) references jpa.events;
alter table if exists jpa.scores add constraint FKmhr6nu0xje0kgubcx0j405gwq foreign key (match_id) references jpa.matches;
alter table if exists jpa.scores add constraint FK4akpbasxcjp3h2uind72q1gqm foreign key (player_id) references jpa.players;
alter table if exists jpa.scores add constraint FKs3t291q06nrji21wr6m8n9gvs foreign key (round_id) references jpa.rounds;
alter table if exists jpa.wins add constraint FKr08ev1nsa6ve7mqccee0m6lwi foreign key (match_id) references jpa.matches;
alter table if exists jpa.wins add constraint FK9ibuqdsn0db7pqadj02bpw23i foreign key (player_id) references jpa.players;
alter table if exists jpa.wins add constraint FK6wd0kd6cat72krn1jrhp26d6h foreign key (team_name) references jpa.teams;
